default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  url: <%= ENV['MY_READER_DEVELOPMENT_DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['MY_READER_TEST_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['MY_READER_PRODUCTION_DATABASE_URL'] %>